meta_product_name: "Curators"
meta_title: "Curators - The social network for art enthusiasts"
meta_description: "Relevant description"
meta_image: "og-image.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
